# This script is used to convert a address QA into a multi-choice question for evaluation.

import os
import argparse
import pandas as pd
from tqdm import tqdm
import json
import csv

from config import RESULTS_PATH, EVAL_COMMON_PATH
from serving.llm_api import extract_choice
from serving.vlm_serving import VLMWrapper

datasets_path_mapping = {
    "llava-bench": "llava-bench-in-the-wild",
    "MMStar": "MMStar",
    "realworldqa": "realworldqa",
    "mm-vet": "MM-Vet/mm-vet",
}

def get_judgeing_prompt(target:str, reference:str):

    rtn = f"""
    Here is a response generated by a LLM, you need to evaluate this response based on a given reference response.
    Reference response: {reference}
    Response: {target}
    Please only give me a score from 1 to 100, where 1 means the response is completely wrong, and 100 means the response is completely correct. If the response is partially correct, please give a score between 1 and 100.
    """

    return rtn.strip()

def mm_vet_get_judging_prompt(question:str, gt:str, model_reply:str):
    prompt = """Compare the ground truth and prediction from AI models, to give a correctness score for the prediction. <AND> in the ground truth means it is totally right only when all elements in the ground truth are present in the prediction, and <OR> means it is totally right when any one element in the ground truth is present in the prediction. The correctness score is 0.0 (totally wrong), 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, or 1.0 (totally right). Just complete the last space of the correctness score.

    Question | Ground truth | Prediction | Correctness
    --- | --- | --- | ---
    What is x in the equation? | -1 <AND> -5 | x = 3 | 0.0
    What is x in the equation? | -1 <AND> -5 | x = -1 | 0.5
    What is x in the equation? | -1 <AND> -5 | x = -5 | 0.5
    What is x in the equation? | -1 <AND> -5 | x = -5 or 5 | 0.5
    What is x in the equation? | -1 <AND> -5 | x = -1 or x = -5 | 1.0
    Can you explain this meme? | This meme is poking fun at the fact that the names of the countries Iceland and Greenland are misleading. Despite its name, Iceland is known for its beautiful green landscapes, while Greenland is mostly covered in ice and snow. The meme is saying that the person has trust issues because the names of these countries do not accurately represent their landscapes. | The meme talks about Iceland and Greenland. It's pointing out that despite their names, Iceland is not very icy and Greenland isn't very green. | 0.4
    Can you explain this meme? | This meme is poking fun at the fact that the names of the countries Iceland and Greenland are misleading. Despite its name, Iceland is known for its beautiful green landscapes, while Greenland is mostly covered in ice and snow. The meme is saying that the person has trust issues because the names of these countries do not accurately represent their landscapes. | The meme is using humor to point out the misleading nature of Iceland's and Greenland's names. Iceland, despite its name, has lush green landscapes while Greenland is mostly covered in ice and snow. The text 'This is why I have trust issues' is a playful way to suggest that these contradictions can lead to distrust or confusion. The humor in this meme is derived from the unexpected contrast between the names of the countries and their actual physical characteristics. | 1.0
    """
    rtn = prompt + "\n" + f"{question} | {gt} | {model_reply} |" + "\nPredict the correctness of the answer (digit): "
    return rtn

import re

def extract_gpt_score(gpt_reply: str):
    gpt_reply = gpt_reply.strip()
    try:
        # Attempt to directly convert the reply to an integer
        score = int(gpt_reply)
    except:
        # Use regular expression to find the first number between 1 and 100
        match = re.search(r'\b(100|[1-9][0-9]?)\b', gpt_reply)
        if match:
            score = int(match.group(0))
        else:
            score = None  # Return None if no valid score is found
            raise ValueError(f"Cannot extract a score from the reply: {gpt_reply}")
    return score


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default="Llama-3-VILA1.5-8b", help='model to be evaluated')
    args = parser.parse_args()
    model_name = args.model_name

    

    model_wrapper = VLMWrapper("GPT4o")
    model = model_wrapper.get_vlm_model()    
    
    # Do the model evaluation on llava-bench
    # dir1 = os.path.join(EVAL_COMMON_PATH, datasets_path_mapping["llava-bench"])
    # # Find all the _response.jsonl files in the directory

    # response_file = os.path.join(dir1, f"{model_name}_response.jsonl")

    # print(f"Start scoring the model on {response_file}")
    # gpt_scores = []
    # response_file = os.path.join(dir1, response_file)
    # model_name = response_file.split("/")[-1].split("_")[0]
    # with open(response_file, 'r') as f:
    #     responses = [json.loads(line) for line in f.readlines()]
    
    # for response in tqdm(responses):
    #     prompt = response["prompt"]
    #     model_reply = response["response"]
    #     gt = response["gt"]


    #     judgeing_prompt = get_judgeing_prompt(model_reply, gt)
    #     # print("++++++++++++++++++++++++++++++++++++++++++")
    #     # print(judgeing_prompt)
    #     gpt_reply = model.generate([judgeing_prompt])
    #     # print("==========================================")
    #     # print(gpt_reply)
    #     # print("------------------------------------------")
    #     # exit()
    #     gpt_scores.append(extract_gpt_score(gpt_reply))

    # # Save the gpt_scores to a file
    # average_score = sum(gpt_scores) / len(gpt_scores)
    # std_score = pd.Series(gpt_scores).std()
    # stats = {
    #     "model_name": model_name,
    #     "average_score": average_score,
    #     "score_std": std_score
    # }
    # gpt_scores_file = os.path.join(RESULTS_PATH, f"{model_name}_llava-bench_results.json")
    # with open(gpt_scores_file, 'w') as f:
    #     json.dump(stats, f, indent=4)
    

    # print(f"Save the gpt_scores to {gpt_scores_file}")


    # # Do the model evaluation on MMStar
    # dir2 = os.path.join(EVAL_COMMON_PATH, datasets_path_mapping["MMStar"])
    # # Find all the _response.jsonl files in the directory

    # response_file = os.path.join(dir2, f"{model_name}_response.jsonl")

    # print(f"Start scoring the model on {response_file}")
    # response_file = os.path.join(dir2, response_file)
    # model_name = response_file.split("/")[-1].split("_")[0]
    # with open(response_file, 'r') as f:
    #     responses = [json.loads(line) for line in f.readlines()]
    
    # correct_count = 0

    # for response in tqdm(responses):
    #     prompt = response["prompt"]
    #     model_reply = response["response"]
    #     gt = response["gt"]

    #     # Based on https://github.com/MMStar-Benchmark/MMStar/tree/main/eval
    #     answer = gt.lower().strip().replace('\n', ' ')
    #     predict = model_reply.lower().strip().replace('\n', ' ')

    #     try:
    #         if answer == predict[0]:
    #             correct_count += 1
    #         elif predict[0] == '(' and answer == predict[1]:
    #             correct_count += 1
    #         elif predict[0:7] == 'option ' and answer == predict[7]:
    #             correct_count += 1
    #         elif predict[0:14] == 'the answer is ' and answer == predict[14]:
    #             correct_count += 1
    #     except Exception as e:
    #         pass

    # accuracy = correct_count / len(responses)
    # stats = {
    #     "model_name": model_name,
    #     "accuracy": accuracy
    # }
    # results_file = os.path.join(RESULTS_PATH, f"{model_name}_MMStar_results.json")
    # with open(results_file, 'w') as f:
    #     json.dump(stats, f, indent=4)

    # print(f"Save the results to {results_file}")

    # # Do the model evaluation on realworldqa

    # dir3 = os.path.join(EVAL_COMMON_PATH, datasets_path_mapping["realworldqa"])
    # # Find all the _response.jsonl files in the directory
    # response_file = os.path.join(dir3, f"{model_name}_response.jsonl")
    # print(f"Start scoring the model on {response_file}")
    # response_file = os.path.join(dir3, response_file)
    # model_name = response_file.split("/")[-1].split("_")[0]
    # with open(response_file, 'r') as f:
    #     responses = [json.loads(line) for line in f.readlines()]
    
    # correct_count = 0

    # for response in tqdm(responses):
    #     prompt = response["prompt"]
    #     model_reply = response["response"]
    #     gt = response["gt"]

    #     # Based on
    #     predict = model_reply.lower().strip().replace('\n', ' ')
    #     answer = gt.lower().strip().replace('\n', ' ')
    #     if predict == answer:
    #         correct_count += 1

    # accuracy = correct_count / len(responses)
    # stats = {
    #     "model_name": model_name,
    #     "accuracy": accuracy
    # }
    # results_file = os.path.join(RESULTS_PATH, f"{model_name}_realworldqa_results.json")
    # with open(results_file, 'w') as f:
    #     json.dump(stats, f, indent=4)

    # print(f"Save the results to {results_file}")

    dir4 = os.path.join(EVAL_COMMON_PATH, datasets_path_mapping["mm-vet"])
    # Find all the _response.jsonl files in the directory
    response_file = os.path.join(dir4, f"{model_name}_response.jsonl")
    print(f"Start scoring the model on {response_file}")
    response_file = os.path.join(dir4, response_file)
    model_name = response_file.split("/")[-1].split("_")[0]
    with open(response_file, 'r') as f:
        responses = [json.loads(line) for line in f.readlines()]

    mm_vet_gpt_scores = []

    for response in tqdm(responses):
        prompt = response["prompt"]
        model_reply = response["response"]
        gt = response["gt"]

        # Based on
        mm_vet_judging_prompt = mm_vet_get_judging_prompt(prompt, gt, model_reply)

        success = False
        num_tries = 0
        while not success:
            try:
                gpt_reply = model.generate([mm_vet_judging_prompt])
                score = gpt_reply.strip()
                score = float(score)
                success = True
            except Exception as e:
                print(f"Error: {e}")
                num_tries += 1
                if num_tries > 5:
                    score = 0.0
                    break
        assert 0.0 <= score <= 1.0 and isinstance(score, float), f"Invalid score: {score}"
        mm_vet_gpt_scores.append(score)

    # Save the gpt_scores to a file
    mm_vet_scores_file = os.path.join(RESULTS_PATH, f"{model_name}_mm-vet_results.json")
    stats = {
        "model_name": model_name,
        "average_score": sum(mm_vet_gpt_scores) / len(mm_vet_gpt_scores),
        "score_std": pd.Series(mm_vet_gpt_scores).std()
    }
    with open(mm_vet_scores_file, 'w') as f:
        json.dump(stats, f, indent=4)